"""empty message

Revision ID: 932f00886c3e
Revises: 6ed11ddb76a3
Create Date: 2023-07-31 23:22:02.608812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932f00886c3e'
down_revision = '6ed11ddb76a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
